version: '3.7'

services:
    database_bora:
        image: postgres
        container_name: database_bora
        restart: always
        ports:
          - 5432:5432
        environment:
          - POSTGRES_USER=boraAdmin
          - POSTGRES_PASSWORD=AdminBora#123@
          - POSTGRES_DB=bora
        volumes:
            - pgdata:/data/postgres
     api_projeto:
        build: .
        container_name: api_projeto
        ports:
          - 3333:3333
          - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database_bora
        depends_on: 
            - database_bora

volumes:
    pgdata:
        driver: local