version: '3.7'

services:
  database_finances:
    image: postgres
    container_name: database_finances
    restart: always
    ports:
      - 5430:5432
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    volumes:
      - pgdata:/var/lib/postgresql/data

  api_finances:
    build: .
    container_name: api_finances
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    depends_on: 
      - database_finances

volumes:
  pgdata:
    driver: local
